### PR TITLE
Allow parsing a solitary hyphen as a free argument

### LINKED ISSUE #15: Panic if the only args are "-"
Given this Rust program:

``` rust
extern crate getopts;

use std::env;

fn main() {
    let args: Vec<String> = env::args().collect();
    let matches = getopts::Options::new().parse(args);
}
```

The following invocation will create a panic:

```
$ ./demonstrate_bug -
thread '<main>' panicked at 'index out of bounds: the len is 1 but the index is 1', src/main.rs:1
```

This is using version getopts 0.2.4 with rustc 1.0.0-nightly (6c065fc8c 2015-02-17).

### PR DESCRIPTION
**Pull request by shepmaster**
Fixes #15

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks!

**Comment by filsmick** [comment]
Please consider bumping the version number; I used getopts before this patch landed, and I can't get cargo to update it it there is no version change.

**Comment by alexcrichton** [comment]
@filsmick published!

**Comment by shepmaster** [comment]
Thank you for your effort on maintaining so many crates, @alexcrichton !

**Comment by filsmick** [comment]
Yes, thank you :+1:

**Pull request merged**
