### PR TITLE
handle sufficient options gracefully refer #46.

### PR DESCRIPTION
**Pull request by prataprc**
Consider this patch as a possible solution, and if there are any alternate ideas please let know. Thanks,

### CODE REVIEW

**Comment by KodrAus** [comment]
Thanks for the PR @prataprc!

Hmm, I'm not sure we should be special casing these two names here. Localization is one potential problem.

As an aside, I would probably try solve the problem put forward in #46 slightly differently. I think the issue is that we've really got multiple distinct commands we're trying to handle (which is where `clap`'s API becomes really useful). We've got the help command and the main running program.

So I would do something like this using the current `getopts` API:

```rust
extern crate getopts;

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let args = &args[1..];

    // Check whether the help args match
    if help_opts().parse(args).ok().map(|matches| matches.opt_present("h")).unwrap_or(false) {
        print!("{}", all_opts().usage("Usage: myprogram [options]"));
        std::process::exit(0)
    }

    // Expect the command args to match or exit with a message
    let matches = command_opts().parse(args).unwrap_or_else(|e| {
        println!("Error: {}", e);
        print!("{}", all_opts().usage("Usage: myprogram [options]"));
        std::process::exit(1)
    });

    println!("Running program");
}

// Our program options
// 
// We use `all_opts` when printing usage
// But the `help` and `command` options are exclusive

fn all_opts() -> getopts::Options {
    let mut opts = getopts::Options::new();
    set_help_opts(&mut opts);
    set_command_opts(&mut opts);

    opts
}

fn command_opts() -> getopts::Options {
    let mut opts = getopts::Options::new();
    set_command_opts(&mut opts);

    opts
}

fn set_command_opts(opts: &mut getopts::Options) {
    opts.reqopt("R", "required", "Required option", "VALUE");
}

fn help_opts() -> getopts::Options {
    let mut opts = getopts::Options::new();
    set_help_opts(&mut opts);
    
    opts
}

fn set_help_opts(opts: &mut getopts::Options) {
    opts.optflag("h", "help", "print this help menu and exit");
}
```

Maybe we could look at ways to make it more ergonomic to deal with sets of options you might want to match?

**Comment by KodrAus** [comment]
This approach definitely has simplicity on its side. I think it would be good to work through the idea of _sufficient options_ a bit. I'm a little worried that the semantics don't make it really clear how we're meant to use them, but this might just need some docs. Personally, I don't find required options super useful, since you need to unwrap them from `Matches` anyways.

So the idea is that you have a few paths your program can take, depending on the presence of sufficient options? A sufficient option is basically a separate path where the appearance of other options (required or otherwise) isn't important because they won't be used. Just based on how we parse things, each sufficient option would be its own path because the presence of one doesn't imply the presence of another. They're most likely going to be independent, informational options like `help` and `version`.

That means we basically have 2 levels of arguments that can be used in `getopts`:

- One of the sufficient options or
- The required + optional options

That seems ok to me, but maybe there's a clearer term than _sufficient_ we could use here?

**Comment by prataprc** [comment]
I have amended the documentation for `reqopt` describing the use case for `Sufficient` HasArg. Sometime naming is more difficult than programming logic 😄. Please suggest an apt name. We can also allow this PR to soak for a while before deciding on the current implementation.

**Comment by KodrAus** [comment]
It's been a few years here and we've become very careful about making changes to the way arguments are parsed to avoid any potential breakage.

I'll go ahead and close this one but thanks for putting the effort in @prataprc!

**Pull request closed without merging**
